server:
  port: 8080
spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    url: jdbc:mysql://localhost:3306/cloud_order?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: Lee
    password: 010426Kenshin
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: orderservice # user的服务名称
  cloud:
    nacos:
      server-addr: localhost:8848 # nacos服务地址
      discovery:
        cluster-name: HZ # 集群名称，这里HZ指杭州
        # namespace: d83898bc-802f-48ce-a6cd-a29abf3bf42f # dev 环境隔离
        # ephemeral: false # 非临时示例
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:10086/eureka
userservice: # 要做配置的微服务名称
  ribbon:
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule  # 负载均衡规则，最近集群随机
# xxxservice: # 要配置的微服务名称
#   ribbon:
#     NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule # 随机访问
# ribbon:
#   eager-load:
#     enabled: true # 开启饥饿加载
#     clients: # 指定饥饿加载的服务名称
#       - userservice
